
import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { atomDark } from 'react-syntax-highlighter/dist/esm/styles/prism';

interface MarkdownRendererProps {
  content: string;
  className?: string;
}

const MarkdownRenderer: React.FC<MarkdownRendererProps> = ({ content, className = "" }) => {
  return (
    <div className={`markdown-content ${className}`}>
      <ReactMarkdown
        remarkPlugins={[remarkMath]}
        rehypePlugins={[rehypeKatex]}
        components={{
          code({ node, inline, className, children, ...props }: any) {
            const match = /language-(\w+)/.exec(className || '');
            const language = match ? match[1] : '';
            const codeContent = String(children).replace(/\n$/, '');

            // Special handling for SVG diagrams generated by AI
            if (!inline && language === 'svg') {
              return (
                <div className="my-6 rounded-3xl overflow-hidden border border-slate-700 bg-slate-900 shadow-2xl">
                  <div className="bg-slate-800/50 px-5 py-2 text-[10px] text-cyan-400 font-black uppercase flex justify-between items-center border-b border-slate-700/50">
                    <span className="flex items-center gap-2">
                      <div className="w-1.5 h-1.5 bg-cyan-500 rounded-full animate-pulse"></div>
                      Schematic Diagram (AI Generated)
                    </span>
                    <span className="opacity-50">Visual Output</span>
                  </div>
                  <div 
                    className="p-6 flex justify-center bg-slate-950/50 overflow-x-auto"
                    dangerouslySetInnerHTML={{ __html: codeContent }}
                  />
                </div>
              );
            }

            return !inline && match ? (
              <div className="my-4 rounded-lg overflow-hidden border border-slate-700 shadow-lg">
                <div className="bg-slate-800 px-4 py-1 text-[10px] text-slate-400 font-mono uppercase flex justify-between items-center border-b border-slate-700">
                  <span>{language}</span>
                  <span className="opacity-50">Code Block</span>
                </div>
                <SyntaxHighlighter
                  style={atomDark}
                  language={language}
                  PreTag="div"
                  customStyle={{ margin: 0, padding: '1rem', fontSize: '0.85rem' }}
                  {...props}
                >
                  {codeContent}
                </SyntaxHighlighter>
              </div>
            ) : (
              <code className={`${className} bg-slate-800 text-cyan-300 px-1.5 py-0.5 rounded font-mono text-sm`} {...props}>
                {children}
              </code>
            );
          },
          p: ({ children }) => <p className="mb-4 leading-relaxed text-right">{children}</p>,
          h1: ({ children }) => <h1 className="text-2xl font-bold text-white mt-6 mb-4 text-right">{children}</h1>,
          h2: ({ children }) => <h2 className="text-xl font-bold text-cyan-400 mt-5 mb-3 text-right">{children}</h2>,
          h3: ({ children }) => <h3 className="text-lg font-bold text-slate-200 mt-4 mb-2 text-right">{children}</h3>,
          ul: ({ children }) => <ul className="list-disc list-inside mb-4 space-y-2 text-right">{children}</ul>,
          ol: ({ children }) => <ol className="list-decimal list-inside mb-4 space-y-2 text-right">{children}</ol>,
          blockquote: ({ children }) => <blockquote className="border-r-4 border-cyan-500 bg-cyan-500/5 p-4 my-4 italic rounded-l-lg text-right">{children}</blockquote>,
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  );
};

export default MarkdownRenderer;
